import { MenuItem, Review, Category } from './types';

export const MENU_CATEGORIES: Category[] = [
  {
    id: 'iced_coffee',
    nameKey: 'category_iced_coffee',
    iconName: 'IceCream',
    items: [
      {
        id: 'ic-1',
        name: 'Iced Latte',
        posNum: 1,
        rating: 4.8,
        isPopular: true,
        modelConfig: {
          type: 'iced_cup',
          baseColor: '#5C4033',
          fluidColor: '#E6C2A0',
          details: ['straw', 'ice', 'milk_swirl'],
        },
      },
      {
        id: 'ic-2',
        name: 'Iced americano',
        posNum: 2,
        rating: 4.6,
        isPopular: false,
        modelConfig: {
          type: 'iced_cup',
          baseColor: '#2C1E15',
          fluidColor: '#3D2B1F',
          details: ['ice', 'condensation'],
        },
      },
      {
        id: 'ic-3',
        name: 'Iced mocha',
        posNum: 3,
        rating: 4.9,
        isPopular: true,
        modelConfig: {
          type: 'iced_cup',
          baseColor: '#3D2314',
          fluidColor: '#5C3317',
          toppingColor: '#FFFDF6',
          details: ['cream', 'chocolate_drizzle', 'straw', 'ice'],
        },
      },
      {
        id: 'ic-4',
        name: 'Iced carmel latte',
        posNum: 4,
        rating: 4.7,
        isPopular: false,
        modelConfig: {
          type: 'iced_cup',
          baseColor: '#4A2C11',
          fluidColor: '#C68E4F',
          toppingColor: '#F59E0B',
          details: ['cream', 'caramel_drizzle', 'straw', 'ice'],
        },
      },
      {
        id: 'ic-5',
        name: 'Iced nutella latte',
        posNum: 5,
        rating: 4.9,
        isPopular: true,
        modelConfig: {
          type: 'iced_cup',
          baseColor: '#3D1F05',
          fluidColor: '#6F4E37',
          toppingColor: '#451A03',
          details: ['cream', 'chocolate_drizzle', 'hazelnut_crumbs', 'straw', 'ice'],
        },
      },
      {
        id: 'ic-6',
        name: 'Iced spanish latte',
        posNum: 6,
        rating: 4.8,
        isPopular: false,
        modelConfig: {
          type: 'iced_cup',
          baseColor: '#5B3E31',
          fluidColor: '#FDF4E3',
          details: ['straw', 'ice', 'double_layer'],
        },
      },
      {
        id: 'ic-7',
        name: 'Iced frapii',
        posNum: 7,
        rating: 4.5,
        isPopular: false,
        modelConfig: {
          type: 'iced_cup',
          baseColor: '#8C6239',
          fluidColor: '#BCA380',
          toppingColor: '#FEF3C7',
          details: ['cream', 'chocolate_drizzle', 'rainbow_sprinkles', 'straw'],
        },
      },
      {
        id: 'ic-8',
        name: 'Iced chokllet',
        posNum: 8,
        rating: 4.7,
        isPopular: false,
        modelConfig: {
          type: 'iced_cup',
          baseColor: '#2B1A0A',
          fluidColor: '#522F11',
          toppingColor: '#FFFFFF',
          details: ['cream', 'chocolate_shavings', 'straw', 'ice'],
        },
      },
      {
        id: 'ic-9',
        name: 'Iced long black',
        posNum: 9,
        rating: 4.6,
        isPopular: false,
        modelConfig: {
          type: 'iced_cup',
          baseColor: '#1A0D05',
          fluidColor: '#23150D',
          details: ['ice', 'amber_crema'],
        },
      },
      {
        id: 'ic-10',
        name: 'Iced espresso tonic',
        posNum: 10,
        rating: 4.8,
        isPopular: true,
        modelConfig: {
          type: 'iced_cup',
          baseColor: '#1D1007',
          fluidColor: '#93C5FD',
          details: ['bubbles', 'lemon_slice', 'ice', 'tonic_layer'],
        },
      },
    ],
  },
  {
    id: 'smoothies',
    nameKey: 'category_smoothies',
    iconName: 'CupSoda',
    items: [
      {
        id: 'sm-1',
        name: 'Strawberry',
        posNum: 1,
        rating: 4.8,
        isPopular: true,
        modelConfig: {
          type: 'smoothie_cup',
          baseColor: '#EF4444',
          fluidColor: '#FCA5A5',
          toppingColor: '#FFFFFF',
          details: ['cream', 'strawberry_slice', 'straw'],
        },
      },
      {
        id: 'sm-2',
        name: 'Mojeto',
        posNum: 2,
        rating: 4.9,
        isPopular: true,
        modelConfig: {
          type: 'smoothie_cup',
          baseColor: '#10B981',
          fluidColor: '#D1FAE5',
          details: ['mint_leaves', 'lime_wheel', 'bubbles', 'straw'],
        },
      },
      {
        id: 'sm-3',
        name: 'Mango',
        posNum: 3,
        rating: 4.7,
        isPopular: false,
        modelConfig: {
          type: 'smoothie_cup',
          baseColor: '#F59E0B',
          fluidColor: '#FEF08A',
          toppingColor: '#FFFFFF',
          details: ['cream', 'mango_chunk', 'straw'],
        },
      },
      {
        id: 'sm-4',
        name: 'Blueberry',
        posNum: 4,
        rating: 4.8,
        isPopular: false,
        modelConfig: {
          type: 'smoothie_cup',
          baseColor: '#4F46E5',
          fluidColor: '#C7D2FE',
          toppingColor: '#FFFFFF',
          details: ['cream', 'blueberry_topping', 'straw'],
        },
      },
      {
        id: 'sm-5',
        name: 'Watermelon',
        posNum: 5,
        rating: 4.6,
        isPopular: false,
        modelConfig: {
          type: 'smoothie_cup',
          baseColor: '#EF4444',
          fluidColor: '#FCA5A5',
          details: ['black_seeds', 'watermelon_tri', 'straw', 'ice'],
        },
      },
      {
        id: 'sm-6',
        name: 'Mix berry',
        posNum: 6,
        rating: 4.9,
        isPopular: true,
        modelConfig: {
          type: 'smoothie_cup',
          baseColor: '#EC4899',
          fluidColor: '#FBCFE8',
          toppingColor: '#FFFFFF',
          details: ['cream', 'berry_drizzle', 'straw'],
        },
      },
      {
        id: 'sm-7',
        name: 'Blue curacoa',
        posNum: 7,
        rating: 4.7,
        isPopular: false,
        modelConfig: {
          type: 'smoothie_cup',
          baseColor: '#06B6D4',
          fluidColor: '#CFFAFE',
          details: ['lime_wheel', 'bubbles', 'straw', 'cherry'],
        },
      },
      {
        id: 'sm-8',
        name: 'Pommeverty',
        posNum: 8,
        rating: 4.5,
        isPopular: false,
        modelConfig: {
          type: 'smoothie_cup',
          baseColor: '#84CC16',
          fluidColor: '#ECFCCB',
          details: ['apple_slice', 'bubbles', 'straw'],
        },
      },
      {
        id: 'sm-9',
        name: 'Peach',
        posNum: 9,
        rating: 4.7,
        isPopular: false,
        modelConfig: {
          type: 'smoothie_cup',
          baseColor: '#F97316',
          fluidColor: '#FFEDD5',
          details: ['peach_slice', 'straw', 'ice_slush'],
        },
      },
      {
        id: 'sm-10',
        name: 'Vanella',
        posNum: 10,
        rating: 4.8,
        isPopular: true,
        modelConfig: {
          type: 'smoothie_cup',
          baseColor: '#D97706',
          fluidColor: '#FEF3C7',
          toppingColor: '#FFFFFF',
          details: ['cream', 'vanilla_spots', 'gold_sprinkles', 'straw'],
        },
      },
    ],
  },
  {
    id: 'sweet',
    nameKey: 'category_sweet',
    iconName: 'Cookie',
    items: [
      {
        id: 'sw-1',
        name: 'Croissants',
        posNum: 1,
        rating: 4.8,
        isPopular: true,
        modelConfig: {
          type: 'croissant',
          baseColor: '#D97706',
          fluidColor: '#FCD34D',
          details: ['crecent_folds', 'butter_shine'],
        },
      },
      {
        id: 'sw-2',
        name: 'Meni Croissants',
        posNum: 2,
        rating: 4.6,
        isPopular: false,
        modelConfig: {
          type: 'croissant',
          baseColor: '#E28743',
          fluidColor: '#FFE0B2',
          details: ['crecent_folds', 'mini_size'],
        },
      },
      {
        id: 'sw-3',
        name: 'Chocolate Croissants',
        posNum: 3,
        rating: 4.9,
        isPopular: true,
        modelConfig: {
          type: 'croissant',
          baseColor: '#D97706',
          fluidColor: '#3F1D0B',
          details: ['crecent_folds', 'chocolate_lines', 'powder_dust'],
        },
      },
      {
        id: 'sw-4',
        name: 'Straawberry Croissants',
        posNum: 4,
        rating: 4.8,
        isPopular: false,
        modelConfig: {
          type: 'croissant',
          baseColor: '#D97706',
          fluidColor: '#FCA5A5',
          toppingColor: '#EF4444',
          details: ['crecent_folds', 'pink_icing', 'cream_filling', 'strawberry_half'],
        },
      },
      {
        id: 'sw-5',
        name: 'Pistachio Croissants',
        posNum: 5,
        rating: 4.9,
        isPopular: true,
        modelConfig: {
          type: 'croissant',
          baseColor: '#D97706',
          fluidColor: '#86EFAC',
          toppingColor: '#15803D',
          details: ['crecent_folds', 'green_drizzle', 'pistachio_nuts'],
        },
      },
      {
        id: 'sw-6',
        name: 'Pop cake',
        posNum: 6,
        rating: 4.7,
        isPopular: false,
        modelConfig: {
          type: 'cake_pop',
          baseColor: '#EC4899',
          fluidColor: '#F472B6',
          toppingColor: '#FFFFFF',
          details: ['stick', 'sprinkles', 'glossy_shell'],
        },
      },
      {
        id: 'sw-7',
        name: 'Mini pan cake',
        posNum: 7,
        rating: 4.7,
        isPopular: false,
        modelConfig: {
          type: 'cake_pancake',
          baseColor: '#F59E0B',
          fluidColor: '#FFFbeb',
          toppingColor: '#B45309',
          details: ['stack_three', 'butter_cube', 'syrup_dripping'],
        },
      },
      {
        id: 'sw-8',
        name: 'Tralicha cake',
        posNum: 8,
        rating: 4.9,
        isPopular: true,
        modelConfig: {
          type: 'cake_slice',
          baseColor: '#FCD34D',
          fluidColor: '#FFFDF0',
          toppingColor: '#D97706',
          details: ['milky_soaked_base', 'caramel_waves', 'white_piping'],
        },
      },
      {
        id: 'sw-9',
        name: 'Darck cake',
        posNum: 9,
        rating: 4.9,
        isPopular: true,
        modelConfig: {
          type: 'cake_slice',
          baseColor: '#3F1D0B',
          fluidColor: '#271003',
          toppingColor: '#F59E0B',
          details: ['layered_chocolate', 'fudge_frosting', 'gold_shimmer'],
        },
      },
      {
        id: 'sw-10',
        name: 'Birthday cake',
        posNum: 10,
        rating: 4.8,
        isPopular: false,
        modelConfig: {
          type: 'cake_slice',
          baseColor: '#60A5FA',
          fluidColor: '#FBCFE8',
          toppingColor: '#EF4444',
          details: ['blue_frosting', 'rainbow_sprinkles', 'glowing_candle'],
        },
      },
    ],
  },
  {
    id: 'coffee',
    nameKey: 'category_coffee',
    iconName: 'Coffee',
    items: [
      {
        id: 'co-1',
        name: 'Shot Espresso',
        posNum: 1,
        rating: 4.7,
        isPopular: false,
        modelConfig: {
          type: 'hot_cup',
          baseColor: '#1F1105',
          fluidColor: '#451A03',
          details: ['crema_swirl', 'demitasse_size'],
        },
      },
      {
        id: 'co-2',
        name: 'Double Espresso',
        posNum: 2,
        rating: 4.8,
        isPopular: false,
        modelConfig: {
          type: 'hot_cup',
          baseColor: '#170B02',
          fluidColor: '#3B1802',
          details: ['rich_crema', 'demitasse_size', 'steam'],
        },
      },
      {
        id: 'co-3',
        name: 'Latte',
        posNum: 3,
        rating: 4.9,
        isPopular: true,
        modelConfig: {
          type: 'hot_cup',
          baseColor: '#5C3D2E',
          fluidColor: '#EAD2AC',
          details: ['latte_art_heart', 'full_size', 'steam'],
        },
      },
      {
        id: 'co-4',
        name: 'Flat white',
        posNum: 4,
        rating: 4.8,
        isPopular: false,
        modelConfig: {
          type: 'hot_cup',
          baseColor: '#55392B',
          fluidColor: '#E6CBA8',
          details: ['flat_microfoam', 'dot_pattern', 'full_size'],
        },
      },
      {
        id: 'co-5',
        name: 'Affogato',
        posNum: 5,
        rating: 4.9,
        isPopular: true,
        modelConfig: {
          type: 'hot_cup',
          baseColor: '#2B1504',
          fluidColor: '#FFFDF6',
          details: ['ice_cream_scoop_inside', 'espresso_drown', 'glass_cup'],
        },
      },
      {
        id: 'co-6',
        name: 'Cappuccino',
        posNum: 6,
        rating: 4.8,
        isPopular: false,
        modelConfig: {
          type: 'hot_cup',
          baseColor: '#5C3D2E',
          fluidColor: '#D2B48C',
          toppingColor: '#5C4033',
          details: ['fluffy_dome_foam', 'cocoa_dust', 'steam', 'full_size'],
        },
      },
      {
        id: 'co-7',
        name: 'Macchiato',
        posNum: 7,
        rating: 4.7,
        isPopular: false,
        modelConfig: {
          type: 'hot_cup',
          baseColor: '#3F2305',
          fluidColor: '#FFFDF6',
          details: ['espresso_base', 'foam_dollop', 'demitasse_size'],
        },
      },
      {
        id: 'co-8',
        name: 'Mocha',
        posNum: 8,
        rating: 4.8,
        isPopular: false,
        modelConfig: {
          type: 'hot_cup',
          baseColor: '#3F1F0A',
          fluidColor: '#6F4E37',
          toppingColor: '#FFFFFF',
          details: ['whipped_cream', 'chocolate_drizzle_lines', 'full_size', 'steam'],
        },
      },
      {
        id: 'co-9',
        name: 'Americano',
        posNum: 9,
        rating: 4.6,
        isPopular: false,
        modelConfig: {
          type: 'hot_cup',
          baseColor: '#251605',
          fluidColor: '#332211',
          details: ['thin_crema_ring', 'full_size'],
        },
      },
      {
        id: 'co-10',
        name: 'Coffee%50',
        posNum: 10,
        rating: 4.7,
        isPopular: true,
        modelConfig: {
          type: 'hot_cup',
          baseColor: '#4A2A11',
          fluidColor: '#CBB296',
          details: ['half_and_half', 'cozy_mug_handle', 'steam'],
        },
      },
    ],
  },
];

export const GUEST_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author: 'Elena Rostova',
    rating: 5,
    avatarColor: 'bg-emerald-100 text-emerald-700',
    quoteKeys: {
      en: '"The Iced Spanish Latte is pure magic—sweet, smooth, and served at the perfect temperature. Visually breathtaking!"',
      ar: '"السبانش لاتيه البارد هنا سحر خالص—حلاوة متوازنة، قوام كريمي رائع، وطريقة تقديم تأسر الأنفاس!"',
      ku: '"ئایس ئیسپانیش لاتیەکە لێرە جادووگەرییەکی تەواوە—شیرینییەکی هاوسەنگ، تامێکی نەرم، و پێشکەشکردنێکی بێوێنە!"',
    },
  },
  {
    id: 'rev-2',
    author: 'Yousef Al-Khafaji',
    rating: 5,
    avatarColor: 'bg-pink-100 text-pink-700',
    quoteKeys: {
      en: '"Absolutely love the pistachio croissant. The flakey crust and rich filling are perfect with the Shot Espresso."',
      ar: '"أعشق كرواسون الفستق هنا! الهشاشة الاستثنائية والحشوة الغنية تتماشى بشكل مثالي مع الإسبريسو."',
      ku: '"کرواسۆنی فستق لێرە شاهانەیە! دەرەوەی تەنک و هێلکەیی و ناوەوەی دەوڵەمەند، لەگەڵ شۆتێک ئیسپریسۆ بێوێنەیە."',
    },
  },
  {
    id: 'rev-3',
    author: 'Kavan Sorani',
    rating: 4.8,
    avatarColor: 'bg-amber-100 text-amber-700',
    quoteKeys: {
      en: '"Visual showcase design is incredible! Being able to rotate and inspect the drinks is so satisfying and modern."',
      ar: '"تصميم العرض البصري مذهل بحق! إمكانية تدوير المشروبات ورؤية التفاصيل جذابة جداً وعصرية."',
      ku: '"دیزاین و پیشاندانی مێنووەکە سەرنجڕاکێشە! توانای سووڕاندنی سێ ڕەهەندی خواردنەوەکان زۆر تایبەت و مۆدێرنە."',
    },
  },
];
